### ISSUE TITLE
User Story 7: Use the Site on Any Device

### ISSUE THREAD

**Issue by Damitwhy** [Damitwhy/Going-Bananaz#11]
# User Story 7: Use the Site on Any Device
   - As a visitor, I want to access the website on any device, so that I can easily find information whether I’m on a desktop, tablet, or mobile. 

## Acceptance Criteria:

     - Responsive design ensuring usability across various devices and screen sizes.
     - Consistent and accessible navigation and layout.
     

## Tasks

- [x] index.html boiler plate and links to css, bootstrap and fontawesome.
- [x] assets folder with images and css folders as children.
- [x] template this for other pages on site.
- [x] semantic tags used to section page , header footer main.
