### ISSUE TITLE
User Story : Landing Page

### ISSUE THREAD

**Issue by Damitwhy** [Damitwhy/Going-Bananaz#14]
As a web developer I want a landing page that allows our users to easily identify what the site is about at first glance so our users will want to interact with and benefit from the site.

## Acceptance Criteria:

- site is visually appealing
- easy to navigate
- contains captivating heading, fonts and images.
- is included in the semantic tag Main

## Tasks:

- [ ] research what is best displayed first
- [ ] gather articles and imagery 
- [ ] discuss and ideate rows columns other team members are using to keep consistency through out site
