### ISSUE TITLE
USER STORY Color Scheme

### ISSUE THREAD

**Issue by Damitwhy** [Damitwhy/Going-Bananaz#16]
As a **site developer** I can **set a color scheme** so that **my visitors will find the site visually appealing**

## Acceptance Criteria:
1. Colors should be appealing recognizing our audience may have problems with sight. maybe nothing too outrageous 
2. that the same color scheme is used throughout the site
3. aria labelling informs user of appealing looks/ imagery/ .etc 

## Tasks: 
- [ ] development team discussion and decision
- [ ] apply color scheme to style.css
- [ ] record with agile story board tasks

**Comment by Damitwhy** [comment]
Colour color chosen by team during huddle...
