### ISSUE TITLE
USER STORY Favicon

### ISSUE THREAD

**Issue by Damitwhy** [Damitwhy/Going-Bananaz#35]
As a **Site User** I can **Clearly make out which site i want to go back to from the Favicon** so that **I can quickly navigate to my favourite pages at a glance**

## Accepted Criteria:
1. Favicon should be easily distinguished from other favicons  
2. be appealing to the eye.
3. be memorable

## Tasks: 
- [x] find or create images
- [x] agree what image best suits our brand
- [x] convert that image to a Favicon
- [x] install it on our site pages upload images to our assets
