### ISSUE TITLE
USER STORY I learn differently

### ISSUE THREAD

**Issue by Damitwhy** [Damitwhy/Going-Bananaz#37]
As a **person with ADHD** I don't like having to read boring pages of waffle to get the information I need  **I prefer videos ** so that **I can hear and see an explanation to learn more quickly**

## Accepted Criteria:
1. video links to videos off site
2. tutorials in line with our brand
3. embedding video on site

## Tasks: 
- [ ] research videos explaining diversity. self help videos for those experiencing discrimination, feelgood videos of diversity success stories
- [ ] find html embedding tech, links, sights
- [ ] include them on site with required aria labelling
